// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantPOS.DataAccessObjects;

#nullable disable

namespace RestaurantPOS.DataAccessObjects.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708135338_AddShiftIdToPayment")]
    partial class AddShiftIdToPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("LowStockThreshold")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("QuantityInStock")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            IngredientName = "Chicken",
                            LowStockThreshold = 3m,
                            QuantityInStock = 20m,
                            Unit = "kg"
                        },
                        new
                        {
                            IngredientId = 2,
                            IngredientName = "Rice",
                            LowStockThreshold = 5m,
                            QuantityInStock = 30m,
                            Unit = "kg"
                        },
                        new
                        {
                            IngredientId = 3,
                            IngredientName = "Beef",
                            LowStockThreshold = 3m,
                            QuantityInStock = 15m,
                            Unit = "kg"
                        },
                        new
                        {
                            IngredientId = 4,
                            IngredientName = "Rice Noodle",
                            LowStockThreshold = 4m,
                            QuantityInStock = 20m,
                            Unit = "kg"
                        },
                        new
                        {
                            IngredientId = 5,
                            IngredientName = "Tea Leaves",
                            LowStockThreshold = 1m,
                            QuantityInStock = 5m,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.MenuCategory", b =>
                {
                    b.Property<int>("MenuCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenuCategoryId");

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            MenuCategoryId = 1,
                            CategoryName = "Appetizers"
                        },
                        new
                        {
                            MenuCategoryId = 2,
                            CategoryName = "Main Course"
                        },
                        new
                        {
                            MenuCategoryId = 3,
                            CategoryName = "Beverages"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MenuCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("MenuItemId");

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            IsAvailable = true,
                            ItemName = "Spring Rolls",
                            MenuCategoryId = 1,
                            Price = 45000m
                        },
                        new
                        {
                            MenuItemId = 2,
                            IsAvailable = true,
                            ItemName = "Chicken Rice",
                            MenuCategoryId = 2,
                            Price = 55000m
                        },
                        new
                        {
                            MenuItemId = 3,
                            IsAvailable = true,
                            ItemName = "Beef Noodle Soup",
                            MenuCategoryId = 2,
                            Price = 65000m
                        },
                        new
                        {
                            MenuItemId = 4,
                            IsAvailable = true,
                            ItemName = "Iced Tea",
                            MenuCategoryId = 3,
                            Price = 15000m
                        });
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.MenuItemIngredient", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityRequired")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("MenuItemId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MenuItemIngredients");

                    b.HasData(
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 1,
                            QuantityRequired = 0.3m
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 2,
                            QuantityRequired = 0.2m
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 3,
                            QuantityRequired = 0.25m
                        },
                        new
                        {
                            MenuItemId = 3,
                            IngredientId = 4,
                            QuantityRequired = 0.2m
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 5,
                            QuantityRequired = 0.02m
                        });
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("money");

                    b.Property<int>("CashierUserId")
                        .HasColumnType("int");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("CashierUserId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ShiftId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.RestaurantTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TableId");

                    b.ToTable("RestaurantTables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Capacity = 2,
                            Status = 0,
                            TableName = "T1"
                        },
                        new
                        {
                            TableId = 2,
                            Capacity = 2,
                            Status = 0,
                            TableName = "T2"
                        },
                        new
                        {
                            TableId = 3,
                            Capacity = 4,
                            Status = 0,
                            TableName = "T3"
                        },
                        new
                        {
                            TableId = 4,
                            Capacity = 4,
                            Status = 0,
                            TableName = "T4"
                        },
                        new
                        {
                            TableId = 5,
                            Capacity = 6,
                            Status = 0,
                            TableName = "T5"
                        },
                        new
                        {
                            TableId = 6,
                            Capacity = 6,
                            Status = 0,
                            TableName = "T6"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ClosingCash")
                        .HasColumnType("money");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpeningCash")
                        .HasColumnType("money");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Administrator",
                            PasswordHash = new byte[] { 137, 24, 11, 117, 186, 133, 166, 44, 180, 241, 70, 149, 120, 226, 77, 217, 4, 142, 123, 149, 4, 173, 21, 24, 13, 219, 101, 111, 63, 70, 162, 48 },
                            PasswordSalt = new byte[] { 75, 180, 23, 138, 140, 83, 101, 7, 171, 19, 103, 8, 169, 181, 106, 39 },
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.MenuItem", b =>
                {
                    b.HasOne("RestaurantPOS.BusinessObjects.MenuCategory", "MenuCategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.MenuItemIngredient", b =>
                {
                    b.HasOne("RestaurantPOS.BusinessObjects.Ingredient", "Ingredient")
                        .WithMany("MenuItemIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.BusinessObjects.MenuItem", "MenuItem")
                        .WithMany("MenuItemIngredients")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Order", b =>
                {
                    b.HasOne("RestaurantPOS.BusinessObjects.RestaurantTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.BusinessObjects.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.OrderItem", b =>
                {
                    b.HasOne("RestaurantPOS.BusinessObjects.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.BusinessObjects.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Payment", b =>
                {
                    b.HasOne("RestaurantPOS.BusinessObjects.User", "CashierUser")
                        .WithMany("Payments")
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.BusinessObjects.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("RestaurantPOS.BusinessObjects.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.BusinessObjects.Shift", "Shift")
                        .WithMany("Payments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CashierUser");

                    b.Navigation("Order");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Shift", b =>
                {
                    b.HasOne("RestaurantPOS.BusinessObjects.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Ingredient", b =>
                {
                    b.Navigation("MenuItemIngredients");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.MenuItem", b =>
                {
                    b.Navigation("MenuItemIngredients");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.RestaurantTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.Shift", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RestaurantPOS.BusinessObjects.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
